"""Army × unit-class price multipliers of the adopted model, as tables.

Reads the committed outputs (no refitting): the full-data `FC` fit in
analysis/output/coefficients.csv (multiplier fclass=<faction>|<class>, merged
slices) and the unit list in analysis/output/oof_predictions.csv. A multiplier
is the army's price for that unit class relative to the plain 8/N rating rule:
1 = priced as the rating alone predicts, 0.8 = 20% cheaper. Cells are
ridge-shrunk towards 1 (κ pseudo-units), so cells with one or two units sit
closer to 1 than their raw prices would.

Outputs (analysis/output/):
  faction_class_multipliers.csv       long: one row per army × class with units
  faction_class_multipliers_wide.csv  one row per army, one column per class
  faction_class_multipliers.md        the wide table, readable

    python analysis/fclass_table.py
"""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "analysis" / "output"
CLASSES = ("infantry_line", "infantry_light", "infantry_grenadiers", "infantry_skirmishers", "infantry_militia",
           "infantry_irregulars", "cavalry_light", "cavalry_missile", "cavalry_standard", "cavalry_lancers",
           "cavalry_heavy", "artillery_foot", "artillery_horse")
SHORT = {c: c.replace("infantry_", "inf ").replace("cavalry_", "cav ").replace("artillery_", "art ") for c in CLASSES}


def main() -> int:
    multiplier: dict[tuple[str, str], float] = {}
    with open(OUT / "coefficients.csv", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if r["slice"] == "merged" and r["variant"] == "FC" and r["feature"].startswith("multiplier fclass="):
                faction, cls = r["feature"].split("=", 1)[1].split("|")
                multiplier[(faction, cls)] = float(r["coefficient"])
    units: Counter = Counter()
    army: dict[str, tuple[str, int, str]] = {}
    with open(OUT / "oof_predictions.csv", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if r["slice"] == "merged" and r["model"] != "staff":
                units[(r["faction_key"], r["unit_class"])] += 1
                army[r["faction_key"]] = (r["army_corps_name"], int(r["rating"]), r["side"])
    if set(multiplier) != set(units):
        raise SystemExit("coefficients and unit list disagree — rerun analysis/unit_pricing.py")
    factions = sorted(army, key=lambda f: (army[f][2], army[f][1], army[f][0]))

    with open(OUT / "faction_class_multipliers.csv", "w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh, lineterminator="\r\n")
        w.writerow(["army_corps_name", "faction_key", "rating", "side", "unit_class", "units", "multiplier"])
        for f in factions:
            name, rating, side = army[f]
            for c in CLASSES:
                if (f, c) in multiplier:
                    w.writerow([name, f, rating, side, c, units[(f, c)], f"{multiplier[(f, c)]:.4f}"])
    with open(OUT / "faction_class_multipliers_wide.csv", "w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh, lineterminator="\r\n")
        w.writerow(["army_corps_name", "faction_key", "rating", "side"] + list(CLASSES))
        for f in factions:
            name, rating, side = army[f]
            w.writerow([name, f, rating, side] + [f"{multiplier[(f, c)]:.3f}" if (f, c) in multiplier else ""
                                                  for c in CLASSES])

    lines = ["# Army × unit-class price multipliers (adopted model)", "",
             "Generated by `analysis/fclass_table.py` from the committed `FC` fit. Each value is the army's price "
             "for that unit class relative to the plain 8/N rating rule: **1.000 = priced as the rating alone "
             "predicts**, 0.800 = 20% cheaper. Small print = number of units in the cell. Cells are shrunk towards "
             "1 (cells with one or two units only partly reflect their own prices); blank = the army has no such "
             "units. Sorted by side, then rating. These sit on top of the rest of the model, so imperial infantry "
             "additionally carries the side factor ×0.884 (coalition ×1).", ""]
    header = ["army", "N"] + [SHORT[c] for c in CLASSES]
    lines += ["| " + " | ".join(header) + " |", "|" + " --- |" * len(header)]
    group_titles = {"imperial": "**Imperial**", "coalition": "**Coalition**"}
    current = None
    for f in factions:
        name, rating, side = army[f]
        if side != current:
            current = side
            lines.append("| " + group_titles[side] + " |" + " |" * (len(header) - 1))
        cells = []
        for c in CLASSES:
            if (f, c) in multiplier:
                m = multiplier[(f, c)]
                text = f"{m:.3f}"
                if m <= 0.9 or m >= 1.1:
                    text = f"**{text}**"
                cells.append(f"{text} <sub>{units[(f, c)]}</sub>")
            else:
                cells.append("")
        lines.append(f"| {name} | {rating} | " + " | ".join(cells) + " |")
    lines += ["", "Bold = at least 10% off the 8/N rule.", ""]
    (OUT / "faction_class_multipliers.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(multiplier)} cells, {len(factions)} armies → analysis/output/faction_class_multipliers*.csv / .md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
